I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 16, in script
    j "Alright settle down class, as promised we’ll be going over your new assignment for this unit"
Exception: Sayer 'j' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 16, in script
    j "Alright settle down class, as promised we’ll be going over your new assignment for this unit"
  File "renpy/ast.py", line 681, in execute
    who = eval_who(self.who, self.who_fast)
  File "renpy/ast.py", line 574, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'j' is not defined.

Windows-10-10.0.19041
Ren'Py 7.4.11.2266
AC Stats Assignment 1.0
Thu Nov 10 19:37:48 2022
